general:
  name: qm9_seedfixed250_seed_0
  wandb: disabled
  gpus: 1
  resume: null
  test_only: null
  check_val_every_n_epochs: 5
  sample_every_val: 4
  val_check_interval: null
  samples_to_generate: 512
  samples_to_save: 20
  chains_to_save: 1
  log_every_steps: 50
  number_chain_steps: 50
  generated_path: null
  final_model_samples_to_generate: 10000
  final_model_samples_to_save: 30
  final_model_chains_to_save: 20
  num_sample_fold: 1
  evaluate_all_checkpoints: false
  save_samples: true
  validation_selection: null
  generation_seed: null
  strict_generation: false
  max_generation_attempt_factor: 10
  defog_commit: null
  conditional: false
  target: k2
  guidance_weight: 2.0
model:
  transition: marginal
  model: graph_tf
  n_layers: 7
  extra_features: rrwp
  rrwp_steps: 12
  hidden_mlp_dims:
    X: 256
    E: 128
    'y': 128
  hidden_dims:
    dx: 256
    de: 64
    dy: 64
    n_head: 8
    dim_ffX: 256
    dim_ffE: 128
    dim_ffy: 128
  lambda_train:
  - 5
  - 0
train:
  n_epochs: 250
  batch_size: 128
  lr: 0.0002
  clip_grad: null
  save_model: true
  num_workers: 0
  ema_decay: 0
  progress_bar: false
  weight_decay: 1.0e-12
  optimizer: adamw
  seed: 0
  time_distortion: identity
dataset:
  name: qm9
  datadir: /localhome/mirzaei/qm9_defog_lab24_20260914/work/data/seed_0
  remove_h: false
  random_subset: null
  pin_memory: false
  compute_fcd: true
  aromatic: true
sample:
  eta: 0
  omega: 0.05
  sample_steps: 500
  time_distortion: polydec
  search: false
  rdb: general
  rdb_crit: dummy
