#!/usr/bin/env python3
"""Export real dataset splits through the reusable PyG graph contract.

This command prepares the inputs needed to train GraphCL/InfoGraph encoders
without importing or running ``main.py``.  It deliberately reuses the
GraphVAE-REQ dataset loader, feature one-hot builder, BFS implementations, and
split functions so the exported feature channels match graph artifacts later
written by ``main.py``.

The output is generator-independent:

* ``real_train_graphs.pt`` is the only collection used for encoder training;
* ``real_validation_graphs.pt`` is written for three-way splits;
* ``real_test_graphs.pt`` is the held-out reference for eventual evaluation;
* every collection has a restricted tensor-only payload and JSON manifest.

Graphs are normalized to the deterministic largest connected component.
Categorical node and edge values remain grouped one-hot features; no degree,
clustering, or other topology-derived attributes are synthesized.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from pathlib import Path
from typing import Sequence

import numpy as np


REPO_ROOT = Path(__file__).resolve().parents[1]
GRAPH_EVALUATION_SRC = REPO_ROOT / "graph_evaluation" / "src"
for source_path in (REPO_ROOT, GRAPH_EVALUATION_SRC):
    source_text = str(source_path)
    if source_text not in sys.path:
        sys.path.insert(0, source_text)

from data import (  # noqa: E402
    BFS,
    BFS_all_components,
    data_split,
    data_split_three_way,
    list_graph_loader,
)
from eval.attributed_gin import graph_from_dense_attributes  # noqa: E402
from ggm_eval import save_pyg_collection  # noqa: E402
from ggm_eval.adapters import attributed_arrays_to_pyg  # noqa: E402
from ggm_eval.datasets import normalize_dataset_name  # noqa: E402
from util import build_onehot_features  # noqa: E402


SPLIT_MODES = ("legacy_80_20", "paper_70_10_20")
BFS_STRATEGIES = ("none", "legacy_first_component", "all_components")


def base_feature_schema(
    dataset: str,
    *,
    tu_attribute_bins: int,
    tu_max_nodes: int | None,
) -> str:
    """Mirror the feature-schema identity generated by ``main.py``."""

    if dataset in {"AIDS", "ENZYMES"}:
        return (
            f"tu-quantile{int(tu_attribute_bins)}-"
            f"max{tu_max_nodes or 'all'}"
        )
    if dataset in {"MUTAG", "PTC"}:
        return "gin-node-label-v2"
    return "default"


def split_fractions(
    split_mode: str,
    train_fraction: float | None,
    val_fraction: float | None,
) -> tuple[float, float]:
    """Resolve the same default fractions used by the training entrypoint."""

    if split_mode == "paper_70_10_20":
        train = 0.7 if train_fraction is None else float(train_fraction)
        validation = 0.1 if val_fraction is None else float(val_fraction)
    elif split_mode == "legacy_80_20":
        train = 0.8 if train_fraction is None else float(train_fraction)
        validation = 0.0 if val_fraction is None else float(val_fraction)
        if validation != 0.0:
            raise ValueError(
                "legacy_80_20 does not support a nonzero validation fraction."
            )
    else:
        raise ValueError(f"Unknown split mode: {split_mode!r}.")
    if not 0.0 < train < 1.0:
        raise ValueError(f"train_fraction must be in (0, 1), got {train}.")
    if not 0.0 <= validation < 1.0:
        raise ValueError(
            f"val_fraction must be in [0, 1), got {validation}."
        )
    if train + validation >= 1.0:
        raise ValueError("Split fractions must leave a non-empty test fraction.")
    return train, validation


def feature_mode_for_collections(
    node_onehot: Sequence,
    edge_onehot: Sequence,
) -> str:
    """Describe the natural decoded feature view for the dataset."""

    has_node = any(value is not None for value in node_onehot)
    has_edge = any(value is not None for value in edge_onehot)
    if has_node and has_edge:
        return "decoded_node_edge"
    if has_node:
        return "decoded_node"
    if has_edge:
        return "decoded_edge"
    return "topology_control"


def graphs_to_pyg(
    adjacencies: Sequence,
    node_values: Sequence | None,
    edge_values: Sequence | None,
    *,
    node_feature_info,
    edge_feature_info,
    adjacency_threshold: float,
    split_name: str,
) -> tuple[list, int]:
    """Convert aligned dense/sparse arrays to strict PyG graphs."""

    node_values = (
        [None] * len(adjacencies)
        if node_values is None
        else list(node_values)
    )
    edge_values = (
        [None] * len(adjacencies)
        if edge_values is None
        else list(edge_values)
    )
    if len(node_values) != len(adjacencies):
        raise ValueError(
            f"{split_name} adjacency/node lengths differ: "
            f"{len(adjacencies)} versus {len(node_values)}."
        )
    if len(edge_values) != len(adjacencies):
        raise ValueError(
            f"{split_name} adjacency/edge lengths differ: "
            f"{len(adjacencies)} versus {len(edge_values)}."
        )

    graphs = []
    rejected = 0
    for index, (adjacency, raw_node, raw_edge) in enumerate(
        zip(adjacencies, node_values, edge_values)
    ):
        if raw_node is None:
            raw_node = np.ones(
                (int(adjacency.shape[0]), 1), dtype=np.float32
            )
        attributed = graph_from_dense_attributes(
            adjacency,
            raw_node,
            raw_edge,
            node_feature_info=(
                node_feature_info if node_values[index] is not None else None
            ),
            edge_feature_info=edge_feature_info,
            values_are_logits=False,
            adjacency_threshold=adjacency_threshold,
        )
        if attributed is None:
            rejected += 1
            continue
        graphs.append(
            attributed_arrays_to_pyg(
                attributed.edges,
                attributed.node_attributes,
                attributed.edge_attributes,
                attributed.source_node_ids,
                name=f"{split_name} graph {index}",
            )
        )
    if not graphs:
        raise ValueError(f"No non-empty graphs remained in the {split_name} split.")
    return graphs, rejected


def _split_dataset(
    split_mode,
    adjacencies,
    labels,
    node_onehot,
    edge_onehot,
    *,
    train_fraction,
    val_fraction,
    split_seed,
):
    """Return named splits while preserving aligned attributes."""

    placeholders = [None] * len(adjacencies)
    if split_mode == "paper_70_10_20":
        result = data_split_three_way(
            graph_lis=adjacencies,
            list_x=placeholders,
            list_label=labels,
            list_node_onehot=node_onehot,
            list_edge_onehot=edge_onehot,
            train_fraction=train_fraction,
            val_fraction=val_fraction,
            seed=split_seed,
        )
        return {
            "train": (result[0], result[9], result[12]),
            "validation": (result[1], result[10], result[13]),
            "reference": (result[2], result[11], result[14]),
        }

    result = data_split(
        graph_lis=adjacencies,
        list_x=placeholders,
        list_label=labels,
        list_node_onehot=node_onehot,
        list_edge_onehot=edge_onehot,
        train_fraction=train_fraction,
        seed=split_seed,
    )
    return {
        "train": (result[0], result[6], result[8]),
        "reference": (result[1], result[7], result[9]),
    }


def export_dataset(args: argparse.Namespace) -> dict:
    """Load, split, normalize, and save one real graph dataset."""

    dataset = normalize_dataset_name(args.dataset)
    train_fraction, val_fraction = split_fractions(
        args.split_mode,
        args.train_fraction,
        args.val_fraction,
    )
    if args.data_dir is not None:
        os.environ["DATA_DIR"] = str(args.data_dir.expanduser().resolve())

    random.seed(args.selection_seed)
    loaded = list_graph_loader(
        dataset,
        _max_list_size=(args.max_graphs or None),
        limited_to=(args.max_graphs or None),
        return_labels=True,
        tu_attribute_bins=args.tu_attribute_bins,
        tu_max_nodes=args.tu_max_nodes,
    )
    (
        adjacencies,
        _features,
        labels,
        node_features,
        edge_features,
        node_feature_info,
        edge_feature_info,
    ) = loaded
    if len(adjacencies) < 3:
        raise ValueError(
            f"{dataset} needs at least three source graphs, got "
            f"{len(adjacencies)}."
        )

    if args.bfs_strategy == "legacy_first_component":
        adjacencies, node_features, edge_features = BFS(
            adjacencies, node_features, edge_features
        )
    elif args.bfs_strategy == "all_components":
        adjacencies, node_features, edge_features = BFS_all_components(
            adjacencies, node_features, edge_features
        )

    (
        node_onehot,
        edge_onehot,
        node_onehot_info,
        edge_onehot_info,
    ) = build_onehot_features(
        node_features,
        edge_features,
        adjacencies,
        node_feature_info,
        edge_feature_info,
    )
    feature_mode = feature_mode_for_collections(node_onehot, edge_onehot)
    feature_schema = (
        base_feature_schema(
            dataset,
            tu_attribute_bins=args.tu_attribute_bins,
            tu_max_nodes=args.tu_max_nodes,
        )
        + f"|export={feature_mode}"
    )
    splits = _split_dataset(
        args.split_mode,
        adjacencies,
        labels,
        node_onehot,
        edge_onehot,
        train_fraction=train_fraction,
        val_fraction=val_fraction,
        split_seed=args.split_seed,
    )

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    filenames = {
        "train": "real_train_graphs.pt",
        "validation": "real_validation_graphs.pt",
        "reference": "real_test_graphs.pt",
    }
    common_metadata = {
        "dataset": dataset,
        "feature_mode": feature_mode,
        "feature_schema": feature_schema,
        "producer": "GraphVAE-REQ/scripts/export_real_pyg_splits.py",
        "selection_seed": int(args.selection_seed),
        "split_seed": int(args.split_seed),
        "split_mode": args.split_mode,
        "train_fraction": train_fraction,
        "validation_fraction": val_fraction,
        "test_fraction": 1.0 - train_fraction - val_fraction,
        "source_graph_limit": int(args.max_graphs),
        "bfs_strategy": args.bfs_strategy,
    }

    artifacts = {}
    for split_name, (split_adj, split_node, split_edge) in splits.items():
        pyg_graphs, rejected = graphs_to_pyg(
            split_adj,
            split_node,
            split_edge,
            node_feature_info=node_onehot_info,
            edge_feature_info=edge_onehot_info,
            adjacency_threshold=args.adjacency_threshold,
            split_name=split_name,
        )
        destination = output_dir / filenames[split_name]
        manifest = save_pyg_collection(
            destination,
            pyg_graphs,
            metadata={**common_metadata, "split": split_name},
        )
        artifacts[split_name] = {
            "path": str(destination),
            "manifest": str(destination.with_suffix(".pt.json")),
            "source_graph_count": len(split_adj),
            "rejected_empty_graphs": rejected,
            "summary": manifest["summary"],
            "collection_sha256": manifest["collection_sha256"],
        }

    dimensions = {
        (
            artifact["summary"]["node_feature_dim"],
            artifact["summary"]["edge_feature_dim"],
        )
        for artifact in artifacts.values()
    }
    if len(dimensions) != 1:
        raise ValueError(
            f"Exported split feature dimensions differ: {sorted(dimensions)}."
        )
    training_graphs = artifacts["train"]["summary"]["graph_count"]
    if training_graphs < 2:
        raise ValueError(
            f"GraphCL requires at least two training graphs, got {training_graphs}."
        )

    payload = {
        "dataset": dataset,
        "feature_mode": feature_mode,
        "feature_schema": feature_schema,
        "source_graph_count": len(adjacencies),
        "split": {
            "mode": args.split_mode,
            "train_fraction": train_fraction,
            "validation_fraction": val_fraction,
            "test_fraction": 1.0 - train_fraction - val_fraction,
            "seed": int(args.split_seed),
        },
        "selection_seed": int(args.selection_seed),
        "source_graph_limit": int(args.max_graphs),
        "bfs_strategy": args.bfs_strategy,
        "artifacts": artifacts,
    }
    summary_path = output_dir / "export_summary.json"
    summary_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return payload


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--data-dir", type=Path)
    parser.add_argument(
        "--split-mode",
        choices=SPLIT_MODES,
        default="legacy_80_20",
    )
    parser.add_argument("--train-fraction", type=float)
    parser.add_argument("--val-fraction", type=float)
    parser.add_argument("--split-seed", type=int, default=123)
    parser.add_argument(
        "--selection-seed",
        type=int,
        default=0,
        help="Seed used by list_graph_loader before an optional graph cap.",
    )
    parser.add_argument(
        "--max-graphs",
        type=int,
        default=0,
        help="Zero uses all source graphs; otherwise select this many first.",
    )
    parser.add_argument(
        "--bfs-strategy",
        choices=BFS_STRATEGIES,
        default="all_components",
    )
    parser.add_argument("--tu-attribute-bins", type=int, default=8)
    parser.add_argument("--tu-max-nodes", type=int)
    parser.add_argument("--adjacency-threshold", type=float, default=0.5)
    return parser


def main():
    args = build_parser().parse_args()
    if args.max_graphs < 0:
        raise ValueError("--max-graphs must be non-negative.")
    if args.tu_attribute_bins < 2:
        raise ValueError("--tu-attribute-bins must be at least two.")
    payload = export_dataset(args)
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
