#!/usr/bin/env python3
"""Generate the controlled eight-config Lobster matrix-motif weight sweep."""

from __future__ import annotations

import copy
import csv
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = (
    ROOT
    / "configs/loss_weight_sweeps/lobster_posthoc_selection"
    / "lobster_plain1_1_n1_e1_m0p1_original.yaml"
)
OUTPUT = ROOT / "configs/matrix_motif"
MANIFEST = OUTPUT / "matrix_weight_sweep_manifest.csv"

# The configured training batch is 200. The current 70-graph training split
# therefore runs in one motif-counting chunk, which was verified on a 24 GiB
# TITAN RTX with the full differentiable matrix loss and backward pass.
MOTIF_BATCH_SIZE = 200

BASE_WEIGHT_MODES = (
    ("plain1_1", False, "1/1"),
    ("kia40_2000", True, "40/2000"),
)
MOTIF_WEIGHTS = (
    ("m0p1", 0.1),
    ("m1", 1.0),
)
TEMPERATURE_MODES = (
    (
        "constant",
        {
            "motif_temperature_start": 1.0,
            "motif_temperature_end": 1.0,
            "motif_temperature_anneal_start_frac": 1.0,
            "motif_temperature_guard_ratio": 0.0,
        },
    ),
    (
        "annealed",
        {
            "motif_temperature_start": 1.0,
            "motif_temperature_end": 0.5,
            "motif_temperature_anneal_start_frac": 0.5,
            "motif_temperature_guard_ratio": 2.0,
        },
    ),
)


def main() -> None:
    template = yaml.safe_load(TEMPLATE.read_text(encoding="utf-8"))
    OUTPUT.mkdir(parents=True, exist_ok=True)
    rows = []

    for base_name, use_kia_weights, bce_kl_label in BASE_WEIGHT_MODES:
        for motif_token, motif_weight in MOTIF_WEIGHTS:
            for temperature_name, temperature_settings in TEMPERATURE_MODES:
                config = copy.deepcopy(template)
                data = config["data"]
                motif = config["motif"]
                loss = config["loss"]
                runtime = config["runtime"]

                # Match the old-v1 Lobster data/cache setup used by the
                # posthoc weight sweep so only the intended matrix experiment
                # factors differ.
                data["database_name"] = "lobster_undir_feat_snap_85093d"
                data["lobster_feature_schema"] = "old_v1"

                motif.update(
                    {
                        "motif_loss": True,
                        "motif_output_mode": "matrix",
                        "use_syntactic_literal_rules": False,
                        "syntactic_literal_rule_mode": "original",
                        "motif_loss_mode": "calibrated_gaussian",
                        **temperature_settings,
                        "motif_temperature_guard_relax_factor": 1.05,
                        "motif_temperature_guard_sharpen_factor": 0.995,
                        "rule_prune": True,
                        "motif_batch_size": MOTIF_BATCH_SIZE,
                        "prepare_motif_cache_only": False,
                    }
                )

                loss.update(
                    {
                        "alpha_kernel_cost": 1.0,
                        "use_graphvae_mm_bce_kl_weights": use_kia_weights,
                        "alpha_node_feat": 1.0,
                        "alpha_edge_feat": 1.0,
                        "alpha_motif_loss": motif_weight,
                        # Original-only rules make the literal group inactive.
                        "alpha_syntactic_literal_motif_loss": 0.0,
                        "alpha_adj_recon": 0.0,
                    }
                )

                stem = (
                    f"lobster_matrix_{base_name}_n1_e1_{motif_token}"
                    f"_original_{temperature_name}"
                )
                runtime.update(
                    {
                        "run_label": stem,
                        "graph_save_path": f"runs/matrix_motif/weight_sweep/{stem}",
                        "dataset_cache_dir": "runs/cluster_tests/lobster_old_features/dataset_cache",
                        "motif_cache_dir": "cache_motifs_old_lobster",
                        "keep_best_validation_mmd": False,
                        "save_validation_checkpoints": False,
                        "checkpoint_interval_epochs": 4000,
                        "third_party_eval": False,
                    }
                )

                output_path = OUTPUT / f"{stem}.yaml"
                header = (
                    "# Generated by scripts/generate_lobster_matrix_motif_sweep.py.\n"
                    "# LOBSTER matrix-valued motif weight-sweep configuration.\n"
                )
                output_path.write_text(
                    header + yaml.safe_dump(config, sort_keys=False),
                    encoding="utf-8",
                )
                rows.append(
                    {
                        "config": str(output_path.relative_to(ROOT)),
                        "bce_kl": bce_kl_label,
                        "node": 1.0,
                        "edge": 1.0,
                        "motif": motif_weight,
                        "temperature": temperature_name,
                        "motif_output_mode": "matrix",
                        "rule_mode": "original",
                        "motif_batch_size": MOTIF_BATCH_SIZE,
                    }
                )

    with MANIFEST.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    print(f"Generated {len(rows)} configs and {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
